// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "superchatbot-blockstack-app",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d7s5re1z5rti1.cloudfront.net"
};


export default awsmobile;
